/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.jdto.mule;

import static org.junit.Assert.*;
import org.junit.Test;
import org.mule.api.MuleMessage;
import org.mule.api.client.MuleClient;
import org.mule.tck.junit4.FunctionalTestCase;


/**
 * Check the sanity of JDTO Binder as a message processor.
 * @author Juan Alberto López Cavallotti
 */
public class JDTOTransformerModuleTest extends FunctionalTestCase {

    @Override
    protected String getConfigResources() {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception {
        
        MuleClient client = muleContext.getClient();
        
        SampleEntity payload = new SampleEntity("This is a sample string");
        
        MuleMessage msg = client.send("vm://MainFlow", payload, null);
        
        Object resultPayload = msg.getPayload();
        
        //check the result
        assertTrue(resultPayload instanceof SampleDTO);
        
        SampleDTO result = (SampleDTO) resultPayload;
        
        //dummy test
        assertEquals(payload.getSourceString(), result.getTargetString());
    }
}
